FROM alpine
RUN apk add --no-cache wget tar openjdk8  && mkdir /opt/tomcat && mkdir /opt/for_tom && wget https://downloads.apache.org/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz && tar xvf apache-tomcat-*tar.gz -C /opt/tomcat --strip-components=1
RUN cp /opt/for_tom/test.war /opt/tomcat/webapps
EXPOSE 8080
ENTRYPOINT ["/opt/tomcat/bin/catalina.sh", "run"]
